export const ORGAOS_JULGADORES_1G = [
  "SEJUD CRIME",
  "SEJUD",
  "VDOC",
  // Varas Criminais - Fortaleza
  "1ª Vara Criminal da Comarca de Fortaleza",
  "2ª Vara Criminal da Comarca de Fortaleza",
  "3ª Vara Criminal da Comarca de Fortaleza",
  "5ª Vara Criminal da Comarca de Fortaleza",
  "6ª Vara Criminal da Comarca de Fortaleza",
  "7ª Vara Criminal da Comarca de Fortaleza",
  "8ª Vara Criminal da Comarca de Fortaleza",
  "9ª Vara Criminal da Comarca de Fortaleza",
  "10ª Vara Criminal da Comarca de Fortaleza",
  "11ª Vara Criminal da Comarca de Fortaleza",
  "12ª Vara Criminal da Comarca de Fortaleza",
  "13ª Vara Criminal da Comarca de Fortaleza",
  "14ª Vara Criminal da Comarca de Fortaleza",
  "15ª Vara Criminal da Comarca de Fortaleza",
  "16ª Vara Criminal da Comarca de Fortaleza",
  "18ª Vara Criminal da Comarca de Fortaleza",
  // Varas do Júri - Fortaleza
  "1ª Vara do Júri da Comarca de Fortaleza",
  "2ª Vara do Júri da Comarca de Fortaleza",
  "3ª Vara do Júri da Comarca de Fortaleza",
  "4ª Vara do Júri da Comarca de Fortaleza",
  "5ª Vara do Júri da Comarca de Fortaleza",
  "6ª Vara do Júri da Comarca de Fortaleza",
  // Varas de Tráfico - Fortaleza
  "1ª Vara de Delito de Tráfico de Drogas da Comarca de Fortaleza",
  "2ª Vara de Delito de Tráfico de Drogas da Comarca de Fortaleza",
  "3ª Vara de Delito de Tráfico de Drogas da Comarca de Fortaleza",
  "4ª Vara de Delito de Tráfico de Drogas da Comarca de Fortaleza",
  "5ª Vara de Delito de Tráfico de Drogas da Comarca de Fortaleza",
  // Juizados VD - Fortaleza
  "1º Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Fortaleza",
  "2º Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Fortaleza",
  "3º Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Fortaleza",
  "4º Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Fortaleza",
  // Especializadas - Fortaleza
  "Vara de Delitos de Organizações Criminosas",
  "Vara Especializada em Crimes contra a Criança e o Adolescente",
  "Vara Estadual do Meio Ambiente (VEMA)",
  "Vara do Juízo Militar da Comarca de Fortaleza",
  // Núcleos de Custódia
  "Núcleo de Custódia e das Garantias da Comarca de Fortaleza",
  "1º Núcleo Regional de Custódia e das Garantias",
  "2º Núcleo Regional de Custódia e das Garantias",
  "3º Núcleo Regional de Custódia e das Garantias",
  "4º Núcleo Regional de Custódia e das Garantias",
  "5º Núcleo Regional de Custódia e das Garantias",
  "6º Núcleo Regional de Custódia e das Garantias",
  "7º Núcleo Regional de Custódia e das Garantias",
  // Varas Empresariais
  "1ª Vara Empresarial, de Recuperação de Empresas e de Falências do Estado do Ceará",
  "2ª Vara Empresarial, de Recuperação de Empresas e de Falências do Estado do Ceará",
  "3ª Vara Empresarial, de Recuperação de Empresas e de Falências do Estado do Ceará",
  // Caucaia
  "1ª Vara Criminal da Comarca de Caucaia",
  "2ª Vara Criminal da Comarca de Caucaia",
  "3ª Vara Criminal da Comarca de Caucaia",
  "4ª Vara Criminal da Comarca de Caucaia",
  "Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Caucaia",
  // Maracanaú
  "1ª Vara Criminal da Comarca de Maracanaú",
  "2ª Vara Criminal da Comarca de Maracanaú",
  "3ª Vara Criminal da Comarca de Maracanaú",
  "Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Maracanaú",
  // Sobral
  "1ª Vara Criminal da Comarca de Sobral",
  "2ª Vara Criminal da Comarca de Sobral",
  "3ª Vara Criminal da Comarca de Sobral",
  "4ª Vara Criminal da Comarca de Sobral",
  "Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Sobral",
  // Juazeiro do Norte
  "1ª Vara Criminal da Comarca de Juazeiro do Norte",
  "2ª Vara Criminal da Comarca de Juazeiro do Norte",
  "3ª Vara Criminal da Comarca de Juazeiro do Norte",
  "4ª Vara Criminal da Comarca de Juazeiro do Norte",
  "Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Juazeiro do Norte",
  // Crato
  "1ª Vara Criminal da Comarca do Crato",
  "2ª Vara Criminal da Comarca do Crato",
  // Quixadá
  "1ª Vara Criminal da Comarca de Quixadá",
  "2ª Vara Criminal da Comarca de Quixadá",
  "Juizado da Violência Doméstica e Familiar Contra a Mulher da Comarca de Quixadá",
  // Iguatu
  "1ª Vara Criminal da Comarca de Iguatu",
  "2ª Vara Criminal da Comarca de Iguatu",
  // Tauá
  "1ª Vara Criminal da Comarca de Tauá",
  "2ª Vara Criminal da Comarca de Tauá",
  // Outras varas criminais
  "Vara Única Criminal da Comarca de Acopiara",
  "Vara Única Criminal da Comarca de Aquiraz",
  "Vara Única Criminal da Comarca de Aracati",
  "Vara Única Criminal da Comarca de Barbalha",
  "Vara Única Criminal da Comarca de Baturité",
  "Vara Única Criminal da Comarca de Brejo Santo",
  "Vara Única Criminal da Comarca de Canindé",
  "Vara Única Criminal da Comarca de Crateús",
  "Vara Única Criminal da Comarca de Eusébio",
  "Vara Única Criminal da Comarca de Icó",
  "Vara Única Criminal da Comarca de Itapajé",
  "Vara Única Criminal da Comarca de Itapipoca",
  "Vara Única Criminal da Comarca de Limoeiro do Norte",
  "Vara Única Criminal da Comarca de Maranguape",
  "Vara Única Criminal da Comarca de Morada Nova",
  "Vara Única Criminal da Comarca de Russas",
  "Vara Única Criminal da Comarca de Santa Quitéria",
  "Vara Única Criminal da Comarca de Tianguá",
  // Varas Únicas (Comarcas)
  "1ª Vara da Comarca de Acaraú",
  "1ª Vara da Comarca de Beberibe",
  "1ª Vara da Comarca de Boa Viagem",
  "1ª Vara da Comarca de Brejo Santo",
  "1ª Vara da Comarca de Camocim",
  "1ª Vara da Comarca de Cascavel",
  "1ª Vara da Comarca de Granja",
  "1ª Vara da Comarca de Horizonte",
  "1ª Vara da Comarca de Itaitinga",
  "1ª Vara da Comarca de Itapajé",
  "1ª Vara da Comarca de Jaguaribe",
  "1ª Vara da Comarca de Marco",
  "1ª Vara da Comarca de Massapê",
  "1ª Vara da Comarca de Mombaça",
  "1ª Vara da Comarca de Nova Russas",
  "1ª Vara da Comarca de Pacajus",
  "1ª Vara da Comarca de Pacatuba",
  "1ª Vara da Comarca de Quixeramobim",
  "1ª Vara da Comarca de Redenção",
  "1ª Vara da Comarca de Santa Quitéria",
  "1ª Vara da Comarca de São Benedito",
  "1ª Vara da Comarca de São Gonçalo do Amarante",
  "1ª Vara da Comarca de Senador Pompeu",
  "1ª Vara da Comarca de Solonópole",
  "1ª Vara da Comarca de Trairi",
  "1ª Vara da Comarca de Uruburetama",
  "1ª Vara da Comarca de Viçosa do Ceará",
  "Vara Única da Comarca de Aiuaba",
  "Vara Única da Comarca de Alto Santo",
  "Vara Única da Comarca de Amontada",
  "Vara Única da Comarca de Aracoiaba",
  "Vara Única da Comarca de Ararendá",
  "Vara Única da Comarca de Araripe",
  "Vara Única da Comarca de Assaré",
  "Vara Única da Comarca de Aurora",
  "Vara Única da Comarca de Barreira",
  "Vara Única da Comarca de Barro",
  "Vara Única da Comarca de Bela Cruz",
  "Vara Única da Comarca de Campos Sales",
  "Vara Única da Comarca de Capistrano",
  "Vara Única da Comarca de Caridade",
  "Vara Única da Comarca de Cariré",
  "Vara Única da Comarca de Caririaçu",
  "Vara Única da Comarca de Cedro",
  "Vara Única da Comarca de Chaval",
  "Vara Única da Comarca de Chorozinho",
  "Vara Única da Comarca de Coreaú",
  "Vara Única da Comarca de Croatá",
  "Vara Única da Comarca de Cruz",
  "Vara Única da Comarca de Farias Brito",
  "Vara Única da Comarca de Guaiúba",
  "Vara Única da Comarca de Guaraciaba do Norte",
  "Vara Única da Comarca de Ibiapina",
  "Vara Única da Comarca de Icapuí",
  "Vara Única da Comarca de Independência",
  "Vara Única da Comarca de Ipaumirim",
  "Vara Única da Comarca de Ipu",
  "Vara Única da Comarca de Ipueiras",
  "Vara Única da Comarca de Iracema",
  "Vara Única da Comarca de Irauçuba",
  "Vara Única da Comarca de Itarema",
  "Vara Única da Comarca de Jaguaretama",
  "Vara Única da Comarca de Jaguaruana",
  "Vara Única da Comarca de Jardim",
  "Vara Única da Comarca de Jijoca de Jericoacoara",
  "Vara Única da Comarca de Jucás",
  "Vara Única da Comarca de Lavras da Mangabeira",
  "Vara Única da Comarca de Mauriti",
  "Vara Única da Comarca de Meruoca",
  "Vara Única da Comarca de Milagres",
  "Vara Única da Comarca de Missão Velha",
  "Vara Única da Comarca de Monsenhor Tabosa",
  "Vara Única da Comarca de Mucambo",
  "Vara Única da Comarca de Mulungu",
  "Vara Única da Comarca de Nova Olinda",
  "Vara Única da Comarca de Novo Oriente",
  "Vara Única da Comarca de Ocara",
  "Vara Única da Comarca de Orós",
  "Vara Única da Comarca de Pacoti",
  "Vara Única da Comarca de Paraipaba",
  "Vara Única da Comarca de Pedra Branca",
  "Vara Única da Comarca de Pentecoste",
  "Vara Única da Comarca de Pereiro",
  "Vara Única da Comarca de Pindoretama",
  "Vara Única da Comarca de Reriutaba",
  "Vara Única da Comarca de Saboeiro",
  "Vara Única da Comarca de Santana do Acaraú",
  "Vara Única da Comarca de Santana do Cariri",
  "Vara Única da Comarca de São Benedito",
  "Vara Única da Comarca de Tabuleiro do Norte",
  "Vara Única da Comarca de Tamboril",
  "Vara Única da Comarca de Ubajara",
  "Vara Única da Comarca de Umirim",
  "Vara Única da Comarca de Uruoca",
  "Vara Única da Comarca de Várzea Alegre",
] as const;

export const ORGAOS_JULGADORES_2G = [
  // Órgão Especial
  "1º Gabinete do Órgão Especial",
  "2º Gabinete do Órgão Especial",
  "3º Gabinete do Órgão Especial",
  "4º Gabinete do Órgão Especial",
  "5º Gabinete do Órgão Especial",
  "6º Gabinete do Órgão Especial",
  "7º Gabinete do Órgão Especial",
  "8º Gabinete do Órgão Especial",
  "9º Gabinete do Órgão Especial",
  "10º Gabinete do Órgão Especial",
  "11º Gabinete do Órgão Especial",
  "12º Gabinete do Órgão Especial",
  "13º Gabinete do Órgão Especial",
  "14º Gabinete do Órgão Especial",
  "15º Gabinete do Órgão Especial",
  "16º Gabinete do Órgão Especial",
  "Gabinete da Vice-Presidência no Órgão Especial",
  "Gabinete do Corregedor Geral da Justiça no Órgão Especial",
  // Seção Criminal
  "Gabinete da Presidência da Seção Criminal",
  "1º Gabinete da Seção Criminal",
  "2º Gabinete da Seção Criminal",
  "3º Gabinete da Seção Criminal",
  "4º Gabinete da Seção Criminal",
  "5º Gabinete da Seção Criminal",
  "6º Gabinete da Seção Criminal",
  "7º Gabinete da Seção Criminal",
  "8º Gabinete da Seção Criminal",
  "9º Gabinete da Seção Criminal",
  "10º Gabinete da Seção Criminal",
  "11º Gabinete da Seção Criminal",
  "12º Gabinete da Seção Criminal",
  "13º Gabinete da Seção Criminal",
  "14º Gabinete da Seção Criminal",
  "15º Gabinete da Seção Criminal",
  "16º Gabinete da Seção Criminal",
  // 1ª Câmara Criminal
  "Gabinete da Presidência da 1ª Câmara de Direito Criminal",
  "1º Gabinete da 1ª Câmara Criminal",
  "2º Gabinete da 1ª Câmara Criminal",
  "3º Gabinete da 1ª Câmara Criminal",
  "4º Gabinete da 1ª Câmara Criminal",
  // 2ª Câmara Criminal
  "Gabinete da Presidência da 2ª Câmara de Direito Criminal",
  "1º Gabinete da 2ª Câmara Criminal",
  "2º Gabinete da 2ª Câmara Criminal",
  "3º Gabinete da 2ª Câmara Criminal",
  "4º Gabinete da 2ª Câmara Criminal",
  // 3ª Câmara Criminal
  "Gabinete da Presidência da 3ª Câmara de Direito Criminal",
  "1º Gabinete da 3ª Câmara Criminal",
  "2º Gabinete da 3ª Câmara Criminal",
  "3º Gabinete da 3ª Câmara Criminal",
  "4º Gabinete da 3ª Câmara Criminal",
  // 4ª Câmara Criminal
  "Gabinete da Presidência da 4ª Câmara de Direito Criminal",
  "1º Gabinete da 4ª Câmara Criminal",
  "2º Gabinete da 4ª Câmara Criminal",
  "3º Gabinete da 4ª Câmara Criminal",
  "4º Gabinete da 4ª Câmara Criminal",
  // 1ª Turma Recursal
  "Gabinete da Presidência da 1ª Turma Recursal",
  "1º Gabinete da 1ª Turma Recursal",
  "2º Gabinete da 1ª Turma Recursal",
  "3º Gabinete da 1ª Turma Recursal",
  // 2ª Turma Recursal
  "Gabinete da Presidência da 2ª Turma Recursal",
  "1º Gabinete da 2ª Turma Recursal",
  "2º Gabinete da 2ª Turma Recursal",
  "3º Gabinete da 2ª Turma Recursal",
  // 3ª Turma Recursal
  "Gabinete da Presidência da 3ª Turma Recursal",
  "1º Gabinete da 3ª Turma Recursal",
  "2º Gabinete da 3ª Turma Recursal",
  "3º Gabinete da 3ª Turma Recursal",
  // 4ª Turma Recursal
  "Gabinete da Presidência da 4ª Turma Recursal",
  "Presidência da 4ª Turma Recursal",
  "1º Gabinete da 4ª Turma Recursal",
  "2º Gabinete da 4ª Turma Recursal",
  "3º Gabinete da 4ª Turma Recursal",
  // 5ª Turma Recursal
  "Gabinete da Presidência da 5ª Turma Recursal",
  "Presidência da 5ª Turma Recursal",
  // 6ª Turma Recursal
  "Gabinete da Presidência da 6ª Turma Recursal",
  "Presidência da 6ª Turma Recursal",
  // 5ª Turma Recursal Provisória
  "1º Gabinete da 5ª Turma Recursal Provisória",
  "2º Gabinete da 5ª Turma Recursal Provisória",
  "3º Gabinete da 5ª Turma Recursal Provisória",
  // 6ª Turma Recursal Provisória
  "1º Gabinete da 6ª Turma Recursal Provisória",
  "2º Gabinete da 6ª Turma Recursal Provisória",
  "3º Gabinete da 6ª Turma Recursal Provisória",
  // TR1
  "Gabinete 1 - TR1",
  "Gabinete 2 - TR1",
  "Gabinete 3 - TR1",
  // TR2
  "Gabinete 1 - TR2",
  "Gabinete 2 - TR2",
  "Gabinete 3 - TR2",
  // TR3
  "Gabinete 1 - TR3",
  "Gabinete 2 - TR3",
  "Gabinete 3 - TR3",
  // TR4
  "Gabinete 1 - TR4",
  "Gabinete 2 - TR4",
  "Gabinete 3 - TR4",
  // TR5
  "Gabinete 1 - TR5",
  "Gabinete 2 - TR5",
  "Gabinete 3 - TR5",
  // TR6
  "Gabinete 1 - TR6",
  "Gabinete 2 - TR6",
  "Gabinete 3 - TR6",
] as const;

export const TODOS_ORGAOS_JULGADORES = [
  ...ORGAOS_JULGADORES_1G,
  ...ORGAOS_JULGADORES_2G,
];
